package com.fast_pos.fast_pos.adapter.in.mapper;

import com.fast_pos.fast_pos.adapter.in.dto.request.UserRequest;
import com.fast_pos.fast_pos.adapter.in.dto.response.UserResponse;
import com.fast_pos.fast_pos.domain.model.User;
import org.springframework.stereotype.Component;

import java.util.UUID;
@Component
public class UserWebMapper {
    //convert UserRequest (DTO) -> user (Domain)
    public User toDomain(UserRequest request){
        return new User(
                null,
                //id is generated by the persistence layer
                request.getTenantStoreName(),
                request.getName(),
                request.getEmail(),
                request.getPassword(),
                request.getRole()
        );
    }
    //convert User (domain) -> UserResponse (DTO)
    public UserResponse toResponse(User user){
        return new UserResponse(
                user.getId(),
                user.getTenantStoreName(),
                user.getName(),
                user.getEmail(),
                user.getRole()
        );
    }
}
